<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>StyleCopErrorSample</RootNamespace>
    <AssemblyName>StyleCopErrorSample</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>
